// ---- Card data: file -> [name, keywords, description] ----
const C = {
"00_Fool.jpg":["The Fool","New beginnings · Trust · Freedom","A fresh chapter is opening, and it may feel a little scary. You don't need the whole map, just the courage to take the first step. Trust yourself; the path shows itself as you walk."],
"01_Magician.jpg":["The Magician","Willpower · Skill · Action","You already have what you need: talent, ideas and energy. Stop waiting for the perfect moment and focus on one goal. What you start now can really work."],
"02_High_Priestess.jpg":["The High Priestess","Intuition · Mystery · Patience","Not everything is visible yet, and that's okay. Stay quiet, listen to your gut and notice what people don't say. The answer you need is already inside you."],
"03_Empress.jpg":["The Empress","Abundance · Care · Creativity","A season of growth and comfort. Love, creativity and money can bloom if you nurture them patiently. Take care of yourself the way you take care of others."],
"04_Emperor.jpg":["The Emperor","Structure · Discipline · Stability","Time to take charge and build something solid. Set clear rules, protect your boundaries and stay consistent. Steady effort now creates security for later."],
"05_Hierophant.jpg":["The Hierophant","Tradition · Guidance · Learning","Advice from a mentor, teacher or family tradition can help right now. Proven methods bring peace. Ask yourself which beliefs are truly yours and which were inherited."],
"06_Lovers.jpg":["The Lovers","Love · Choice · Alignment","A meaningful connection or an important choice is in front of you. Be honest about what your heart wants. The right decision matches your values, not just your desire."],
"07_Chariot.jpg":["The Chariot","Drive · Victory · Control","Momentum is on your side. Pull your mixed feelings together and move in one direction with confidence. Success comes when distractions don't steer you."],
"Cups05.jpg":["Five of Cups","Loss · Regret · Hope","You are focused on what was lost, and the sadness is real. But look behind you: some cups are still standing. Grieve, then turn around and see what remains."],
"Cups06.jpg":["Six of Cups","Nostalgia · Kindness · Memories","Sweet memories or someone from your past may return. Small acts of kindness and old friendships heal you now. Just don't get stuck living in yesterday."],
"Cups07.jpg":["Seven of Cups","Dreams · Options · Illusion","Too many choices and daydreams are clouding your view, and some only look shiny. Write down what you truly want and pick one thing to work on."],
"Cups08.jpg":["Eight of Cups","Letting go · Moving on · Searching","Something no longer feeds your heart, even if it looks fine outside. Walking away is scary, but staying costs more. It's time to look for deeper meaning."],
"Cups09.jpg":["Nine of Cups","Wishes · Satisfaction · Joy","The wish card. You are close to what you hoped for, or you should feel proud of how far you've come. Enjoy it and be grateful without guilt."],
"Cups10.jpg":["Ten of Cups","Family · Harmony · Happiness","Emotional fulfillment and peaceful relationships. Home, family or a close circle brings real joy. This is what lasting happiness looks like, so cherish it."],
"Cups11.jpg":["Page of Cups","Curiosity · Messages · Sensitivity","A sweet message, a creative idea or a new emotional beginning arrives. Stay open and playful, and follow your intuition even if it seems silly."],
"Cups12.jpg":["Knight of Cups","Romance · Charm · Offers","An invitation, proposal or romantic gesture may come. Lead with your heart but keep your feet on the ground. Charm is lovely; make sure the promises are real."],
"Cups13.jpg":["Queen of Cups","Compassion · Intuition · Care","You feel deeply, and that is your strength. Listen to your emotions and support others without draining yourself. Trust your inner voice in matters of the heart."],
"Pents01.jpg":["Ace of Pentacles","Opportunity · Prosperity · Start","A real chance for money, a job or a new project is being offered. It's practical and it can grow. Say yes and plant the seed."],
"Pents02.jpg":["Two of Pentacles","Balance · Juggling · Adapting","You are handling many things at once: work, money, people. Stay flexible and prioritize. It's manageable as long as you don't drop the important ball."],
"Pents03.jpg":["Three of Pentacles","Teamwork · Skill · Recognition","Your effort gets noticed when you work with others. Ask for feedback and share credit. Quality work builds a strong reputation."],
"Pents04.jpg":["Four of Pentacles","Security · Saving · Control","You are holding tight to money or stability. Saving is wise, but fear of loss may be making you rigid. Protect what's yours without shutting people out."],
"Pents05.jpg":["Five of Pentacles","Hardship · Worry · Support","Tough times, money stress or feeling left out. Help is closer than it seems, you just have to ask. This phase will pass."],
"Pents06.jpg":["Six of Pentacles","Generosity · Giving · Fairness","Giving and receiving are in balance. Someone may help you, or you can help someone else. Give without expecting anything back."],
"Pents07.jpg":["Seven of Pentacles","Patience · Waiting · Review","You've worked hard and now you wait for results. Check that your effort is going in the right direction. Growth takes time, so don't quit before the harvest."],
"Pents08.jpg":["Eight of Pentacles","Practice · Craft · Focus","Improve your skill step by step. Repetition may feel boring, but it builds mastery. Put in the hours and the result will show."],
"Pents09.jpg":["Nine of Pentacles","Independence · Comfort · Self-made","You have earned comfort through your own effort. Enjoy your freedom and treat yourself. Self-reliance is your superpower."],
"Pents10.jpg":["Ten of Pentacles","Legacy · Family · Wealth","Long-term security and lasting success, often shared with family. Think beyond today and build something that lasts."],
"Pents11.jpg":["Page of Pentacles","Learning · Goals · Ambition","A student mindset brings results. Start a course, a skill or a savings plan. Take small practical steps toward a big goal."],
"Pents13.jpg":["Queen of Pentacles","Practical · Nurturing · Abundant","Warm and grounded, you make a home and a life comfortable. Manage money wisely and care for people, and remember to balance work with rest."],
"Pents14.jpg":["King of Pentacles","Success · Security · Leadership","Steady, reliable success. You have built something and can now lead with generosity. Make wise money decisions and stay patient."],
"Swords01.jpg":["Ace of Swords","Clarity · Truth · Breakthrough","A sudden clear thought cuts through confusion. Speak the truth and decide with logic. A new idea or insight is your sharpest tool."],
"Swords02.jpg":["Two of Swords","Indecision · Stalemate · Pause","You are stuck between two choices and avoiding both. Blocking your emotions doesn't help. Gather the facts, then trust yourself and decide."],
"Swords04.jpg":["Four of Swords","Rest · Recovery · Pause","Stop and recharge. Your mind and body need a break before the next step. Rest is productive, not lazy."],
"Swords05.jpg":["Five of Swords","Conflict · Pride · Loss","A fight where winning may cost more than it's worth. Ask yourself if it's worth it. Sometimes walking away protects your peace."],
"Swords06.jpg":["Six of Swords","Moving on · Calmer waters","You are leaving trouble behind and heading somewhere calmer. The journey is slow and a little sad, but it heals. Better days are ahead."],
"Swords07.jpg":["Seven of Swords","Strategy · Secrets · Caution","Someone may be hiding something, or you are avoiding the direct route. Be honest and watch for shortcuts. Trust, but verify."],
"Swords08.jpg":["Eight of Swords","Feeling trapped · Fear · Self-limits","You feel stuck, but the ropes are looser than they look. Fear is holding you more than reality is. Take one small step out."],
"Swords09.jpg":["Nine of Swords","Anxiety · Overthinking · Worry","Worries feel huge at night, and most of it is in your head. Talk to someone you trust; fear shrinks when it is shared."],
"Swords10.jpg":["Ten of Swords","Ending · Rock bottom · Relief","A painful chapter finally ends. It hurts, but the worst is over. From here, the only direction is up."],
"Swords11.jpg":["Page of Swords","Curiosity · Ideas · Questions","Stay curious and keep asking questions. New information or a message arrives. Think before you speak, but don't be afraid to learn."],
"Swords12.jpg":["Knight of Swords","Speed · Ambition · Bluntness","Charging ahead with strong opinions and fast action. Great energy, but watch your words and don't rush without a plan."],
"Swords13.jpg":["Queen of Swords","Honesty · Independence · Clarity","A sharp mind and clear boundaries. You say what you mean and see through excuses. Be truthful, but kind."],
"Swords14.jpg":["King of Swords","Logic · Authority · Fairness","Decide with a calm, clear mind. Use facts, be fair and communicate clearly. Your judgment carries weight."],
"Wands01.jpg":["Ace of Wands","Spark · Inspiration · Energy","A burst of motivation and a fresh creative idea. Act on it while the fire is strong. This could be the start of something exciting."],
"Wands02.jpg":["Two of Wands","Planning · Decisions · Vision","You have taken the first step, now decide where to go next. Plan bigger and look beyond your comfort zone. The world is wide."],
"Wands03.jpg":["Three of Wands","Expansion · Progress · Foresight","Your efforts are launching. Look ahead; opportunities are on the way. Stay patient as results arrive."],
"Wands04.jpg":["Four of Wands","Celebration · Home · Milestone","A happy moment, a gathering or a stable base. Celebrate what you've achieved and enjoy it with the people you love."],
"Wands05.jpg":["Five of Wands","Competition · Friction · Chaos","Lots of opinions and clashes. Competition can sharpen you if you keep it healthy. Don't waste energy on pointless arguments."],
"Wands06.jpg":["Six of Wands","Victory · Recognition · Confidence","Success and public praise. Your hard work is being seen. Accept the applause, but stay humble."],
"Wands07.jpg":["Seven of Wands","Defending · Courage · Standing firm","You are under pressure but in a strong position. Hold your ground and believe in your choice. Don't let others push you off."],
"Wands08.jpg":["Eight of Wands","Speed · News · Momentum","Things move fast: messages, travel or quick progress. Act quickly and keep in touch."],
"Wands09.jpg":["Nine of Wands","Resilience · Fatigue · Almost there","You are worn out but nearly at the finish. Don't give up now. Rest a little, keep your guard up and push through."],
"Wands10.jpg":["Ten of Wands","Burden · Responsibility · Overload","You are carrying too much. Ask for help, delegate and drop what isn't needed. The goal is close, so pace yourself."],
"Wands11.jpg":["Page of Wands","Enthusiasm · Exploring · Ideas","A curious, excited energy. A new interest or an interesting message arrives. Try something new with a playful spirit."],
"Wands12.jpg":["Knight of Wands","Adventure · Passion · Impulse","Bold energy and love of adventure. Great drive, but avoid rushing or overpromising. Channel the fire into one goal."],
"Wands13.jpg":["Queen of Wands","Confidence · Warmth · Charisma","You are magnetic and confident. Own your passion and inspire others. Be independent and brave in what you love."],
"Wands14.jpg":["King of Wands","Vision · Leadership · Boldness","A natural leader with a big vision. Lead by example, inspire people and take bold decisions. Turn ideas into reality."]
};
const deck = Object.entries(C).map(([file,[name,tags,desc]]) => ({file, name, tags: tags.split(' · '), desc}));
